name: Build

on:
  push:
    branches-ignore:
      - 'v4'
      - 'rm'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches-ignore:
      - 'v4'
      - 'rm'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # Publish
      - name: Publish framework-dependent
        run: dotnet publish Shadowsocks.WPF -c Release --no-restore
      # - name: Publish self-contained for Windows ARM64
      #   run: dotnet publish Shadowsocks.WPF -c Release -r win-arm64 --self-contained
      - name: Publish self-contained for Windows x64
        run: dotnet publish Shadowsocks.WPF -c Release -r win-x64 --self-contained
      # Upload
      # - name: Upload artifacts for Windows ARM64
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: shadowsocks-wpf-${{ github.sha }}-windows-arm64
      #     path: Shadowsocks.WPF/bin/Release/net5.0-windows10.0.19041.0/win-arm64/publish/
      - name: Upload artifacts for Windows x64
        uses: actions/upload-artifact@v2
        with:
          name: shadowsocks-wpf-${{ github.sha }}-windows-x64
          path: Shadowsocks.WPF/bin/Release/net5.0-windows10.0.19041.0/win-x64/publish/
      - name: Upload artifacts for Windows framework-dependent
        uses: actions/upload-artifact@v2
        with:
          name: shadowsocks-wpf-${{ github.sha }}-windows
          path: Shadowsocks.WPF/bin/Release/net5.0-windows10.0.19041.0/publish/
